# This is a basic workflow that is manually triggered

name: Build and deploy to GitHUb Pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-site:
    name: Build frontend site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Vuepress to GitHub Pages
        uses: testthedocs/github-pages-deploy-action@0.0.2
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: src/
